# This file describes a conda environment that can be to install the JWST
#   validation notebooks
#
# Run the following command to set up this environment:
# $ conda env create -f environment.yml
#
# The environment name can be overridden with the following command:
# $ conda env create -n <custom name> -f environment.yml
#
# Run the following command to activate the environment:
# $ conda activate jwst_validation_notebooks
#
# To deactivate the environment run the following command:
# $ conda deactivate
#
# To remove the environment entirely, run the following command:
# $ conda env remove -n jwst_validation_notebooks

name: jwst_validation_notebooks

channels:
  - conda-forge
  - astropy
  - http://ssb.stsci.edu/astroconda
  - defaults

dependencies:
  # Base dependencies
  - pip
  - python>=3.6.1,<3.7
  - Cython
  - jupyter
  - nb_conda

  - pip:
    # Major modules
    - numpy
    - astropy
    - matplotlib
    - jupyter
    - ci-watson
    - junit-xml
    - nbformat
    - jinja2
    - ipykernel
    - jwst
    - git+https://github.com/spacetelescope/stsci.imagestats@1.6.2
    - git+https://github.com/mfixstsci/nbpages@add-path-arg
#    - git+https://github.com/spacetelescope/jwst@stable
    - git+https://github.com/spacetelescope/nirspec_pipe_testing_tool@1.1.4
    - git+https://github.com/spacetelescope/pysiaf

variables:
  TEST_BIGDATA: "https://bytesalad.stsci.edu/artifactory"
  CRDS_SERVER_URL: "https://jwst-crds.stsci.edu"

